# Generated by Django 5.0.7 on 2024-07-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visits",
            name="timestamp",
            field=models.DateTimeField(),
        ),
    ]
