# Generated by Django 5.0.7 on 2024-07-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('groups', models.ManyToManyField(to='auth.group')),
                ('permissions', models.ManyToManyField(limit_choices_to={'codename__in': ['basic', 'pro', 'advance', 'basic plus'], 'content_type__app_label': 'subscriptions'}, to='auth.permission')),
            ],
            options={
                'permissions': [('basic', 'Basic Perms'), ('pro', 'Pro Perms'), ('advance', 'Advanced Perms'), ('basic plus', 'Basic Plus Perms')],
            },
        ),
    ]
