# Generated by Django 5.0.7 on 2024-07-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_subscriptions_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
