# Generated by Django 5.0.7 on 2024-08-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_usersubscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='plan_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='product_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
