# Generated by Django 5.0.7 on 2024-08-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_alter_subscriptions_plan_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionprice',
            name='price',
            field=models.DecimalField(decimal_places=0, default=349, max_digits=10),
        ),
    ]
