# Generated by Django 5.0.7 on 2024-08-08 11:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_subscriptionprice_featured_subscriptionprice_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionprice',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
