# Generated by Django 5.0.7 on 2024-08-08 11:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_alter_subscriptionprice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionprice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'ordering': ['order', 'featured', '-updated'], 'permissions': [('basic', 'Basic Permissions'), ('pro', 'Pro Permissions'), ('advance', 'Advanced Permissions'), ('basic plus', 'Basic Plus Permissions')]},
        ),
        migrations.RemoveField(
            model_name='subscriptionprice',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='subscriptionprice',
            name='order',
        ),
        migrations.RemoveField(
            model_name='subscriptionprice',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='subscriptionprice',
            name='updated',
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='order',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
