# Generated by Django 5.0.7 on 2024-08-09 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0012_subscriptionprice_featured_subscriptionprice_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionprice',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='subscriptionprice',
            name='order',
        ),
    ]
