# Generated by Django 5.0.7 on 2024-08-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0014_alter_subscriptionprice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='features',
            field=models.TextField(blank=True, help_text='Features of plan, seperaterd by new line', null=True),
        ),
    ]
